#:schema https://raw.githubusercontent.com/AverseABFun/queerchat/refs/heads/main/queer.json
users = "./queerusers.toml"
prevent_spoofing = true

[motd]
server_name = "Example Server"
login_message = "Hello, user!"

[motd.motd]
is_file = false
text = "This is an example server!!"

[motd.failed_login_message]
invalid_key = "Whoops, invalid key!"
blacklisted = "Ope, you've been blacklisted! Good luck next time!"
not_whitelisted = "You aren't on the whitelist, mate!"
